<?php
/**
 * Single picture collection template.
 *
 * @package PEALIPG
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$pealipg_detail_settings = PEALIPG_Plugin::get_detail_settings();
$pealipg_wrapper_classes = array(
	'pealipg-single-wrapper',
	'pealipg-detail-width-' . $pealipg_detail_settings['width'],
	'pealipg-detail-align-' . $pealipg_detail_settings['alignment'],
	'pealipg-detail-corners-' . $pealipg_detail_settings['corners'],
);
$pealipg_wrapper_style = '';

if ( $pealipg_detail_settings['background_color'] ) {
	$pealipg_wrapper_classes[] = 'pealipg-detail-has-background';
	$pealipg_wrapper_style     = '--pealipg-detail-background:' . $pealipg_detail_settings['background_color'] . ';';
}

get_header();
?>

<main id="primary" class="site-main pealipg-site-main">
	<div class="<?php echo esc_attr( implode( ' ', $pealipg_wrapper_classes ) ); ?>"<?php if ( $pealipg_wrapper_style ) : ?> style="<?php echo esc_attr( $pealipg_wrapper_style ); ?>"<?php endif; ?>>
		<?php while ( have_posts() ) : ?>
			<?php the_post(); ?>
			<article id="post-<?php the_ID(); ?>" <?php post_class( 'pealipg-single-article' ); ?>>
				<?php
				$pealipg_title     = get_the_title();
				$pealipg_has_title = ! empty( $pealipg_title ) && '(no title)' !== $pealipg_title;
				?>

				<?php if ( ( $pealipg_detail_settings['show_title'] && $pealipg_has_title ) || $pealipg_detail_settings['show_date'] ) : ?>
					<header class="pealipg-single-header">
						<?php if ( $pealipg_detail_settings['show_title'] && $pealipg_has_title ) : ?>
							<h1 class="pealipg-single-title"><?php echo esc_html( $pealipg_title ); ?></h1>
						<?php endif; ?>

						<?php if ( $pealipg_detail_settings['show_date'] ) : ?>
							<div class="pealipg-single-date">
								<time datetime="<?php echo esc_attr( get_the_date( DATE_W3C ) ); ?>">
									<?php
									printf(
										/* translators: %s: Publication date. */
										esc_html__( 'Added on %s', 'peal333-infinite-picture-gallery' ),
										esc_html( get_the_date() )
									);
									?>
								</time>
							</div>
						<?php endif; ?>
					</header>
				<?php endif; ?>

				<div class="pealipg-single-content">
					<?php if ( $pealipg_detail_settings['show_cover'] && has_post_thumbnail() ) : ?>
						<div class="pealipg-cover-media">
							<?php
							$pealipg_cover_id   = get_post_thumbnail_id();
							$pealipg_cover      = get_the_post_thumbnail( get_the_ID(), 'large', array( 'class' => 'pealipg-cover-image' ) );
							$pealipg_cover_full = wp_get_attachment_image_url( $pealipg_cover_id, 'full' );
							$pealipg_cover_alt  = get_post_meta( $pealipg_cover_id, '_wp_attachment_image_alt', true );
							?>
							<?php if ( $pealipg_detail_settings['enable_lightbox'] && $pealipg_cover_full ) : ?>
								<button type="button" class="pealipg-lightbox-trigger pealipg-cover-trigger" data-pealipg-lightbox-src="<?php echo esc_url( $pealipg_cover_full ); ?>" data-pealipg-lightbox-alt="<?php echo esc_attr( $pealipg_cover_alt ); ?>" aria-label="<?php echo esc_attr__( 'Open cover photo in lightbox', 'peal333-infinite-picture-gallery' ); ?>">
									<?php
									// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core for the current post.
									echo $pealipg_cover;
									?>
								</button>
							<?php else : ?>
								<?php
								// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core for the current post.
								echo $pealipg_cover;
								?>
							<?php endif; ?>
						</div>
					<?php endif; ?>

					<?php
					$pealipg_description = get_post_meta( get_the_ID(), PEALIPG_Plugin::DESCRIPTION_META_KEY, true );
					if ( $pealipg_detail_settings['show_description'] && ! empty( $pealipg_description ) ) :
						?>
						<div class="pealipg-description">
							<?php echo wp_kses_post( wpautop( $pealipg_description ) ); ?>
						</div>
					<?php endif; ?>
				</div>

				<?php
				$pealipg_gallery_ids = get_post_meta( get_the_ID(), PEALIPG_Plugin::GALLERY_META_KEY, true );
				$pealipg_ids_array   = array_values( array_unique( array_filter( array_map( 'absint', explode( ',', (string) $pealipg_gallery_ids ) ) ) ) );
				$pealipg_media_class = array(
					'pealipg-inner-gallery-grid',
					'pealipg-detail-layout-' . $pealipg_detail_settings['media_layout'],
					'pealipg-detail-columns-' . absint( $pealipg_detail_settings['columns'] ),
					'pealipg-detail-ratio-' . $pealipg_detail_settings['media_ratio'],
					'pealipg-detail-gap-' . $pealipg_detail_settings['gap'],
				);
				if ( ! empty( $pealipg_ids_array ) ) :
					?>
					<div class="<?php echo esc_attr( implode( ' ', $pealipg_media_class ) ); ?>">
						<?php foreach ( $pealipg_ids_array as $pealipg_attachment_id ) : ?>
							<?php
							if ( 'attachment' !== get_post_type( $pealipg_attachment_id ) ) {
								continue;
							}
							?>
							<?php if ( wp_attachment_is( 'video', $pealipg_attachment_id ) ) : ?>
								<?php
								$pealipg_video_url = wp_get_attachment_url( $pealipg_attachment_id );
								$pealipg_mime_type = get_post_mime_type( $pealipg_attachment_id );
								if ( ! $pealipg_video_url ) {
									continue;
								}
								?>
								<figure class="pealipg-detail-media-item">
									<video controls playsinline preload="metadata">
										<source src="<?php echo esc_url( $pealipg_video_url ); ?>#t=0.5" type="<?php echo esc_attr( $pealipg_mime_type ); ?>">
										<?php esc_html_e( 'Your browser does not support the video tag.', 'peal333-infinite-picture-gallery' ); ?>
									</video>
								</figure>
							<?php elseif ( wp_attachment_is( 'image', $pealipg_attachment_id ) ) : ?>
								<?php
								$pealipg_image      = wp_get_attachment_image( $pealipg_attachment_id, 'large', false, array( 'loading' => 'lazy' ) );
								$pealipg_image_full = wp_get_attachment_image_url( $pealipg_attachment_id, 'full' );
								$pealipg_image_alt  = get_post_meta( $pealipg_attachment_id, '_wp_attachment_image_alt', true );
								if ( ! $pealipg_image ) {
									continue;
								}
								?>
								<figure class="pealipg-detail-media-item">
									<?php if ( $pealipg_detail_settings['enable_lightbox'] && $pealipg_image_full ) : ?>
										<button type="button" class="pealipg-lightbox-trigger" data-pealipg-lightbox-src="<?php echo esc_url( $pealipg_image_full ); ?>" data-pealipg-lightbox-alt="<?php echo esc_attr( $pealipg_image_alt ); ?>" aria-label="<?php echo esc_attr__( 'Open image in lightbox', 'peal333-infinite-picture-gallery' ); ?>">
											<?php
											// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core for a known attachment ID.
											echo $pealipg_image;
											?>
										</button>
									<?php else : ?>
										<?php
										// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core for a known attachment ID.
										echo $pealipg_image;
										?>
									<?php endif; ?>
								</figure>
							<?php endif; ?>
						<?php endforeach; ?>
					</div>
				<?php endif; ?>

				<?php if ( $pealipg_detail_settings['show_navigation'] ) : ?>
					<?php
					$pealipg_previous_post  = get_previous_post();
					$pealipg_next_post      = get_next_post();
					$pealipg_previous_title = $pealipg_previous_post ? get_the_title( $pealipg_previous_post ) : '';
					$pealipg_next_title     = $pealipg_next_post ? get_the_title( $pealipg_next_post ) : '';

					if ( '' === trim( $pealipg_previous_title ) ) {
						$pealipg_previous_title = __( 'Untitled picture', 'peal333-infinite-picture-gallery' );
					}
					if ( '' === trim( $pealipg_next_title ) ) {
						$pealipg_next_title = __( 'Untitled picture', 'peal333-infinite-picture-gallery' );
					}
					?>
					<?php if ( $pealipg_previous_post || $pealipg_next_post ) : ?>
						<nav class="pealipg-picture-navigation" aria-label="<?php echo esc_attr__( 'Picture navigation', 'peal333-infinite-picture-gallery' ); ?>">
							<div>
								<?php if ( $pealipg_previous_post ) : ?>
									<a href="<?php echo esc_url( get_permalink( $pealipg_previous_post ) ); ?>" rel="prev"><span><?php esc_html_e( 'Previous Picture', 'peal333-infinite-picture-gallery' ); ?></span><strong><?php echo esc_html( $pealipg_previous_title ); ?></strong></a>
								<?php endif; ?>
							</div>
							<div>
								<?php if ( $pealipg_next_post ) : ?>
									<a href="<?php echo esc_url( get_permalink( $pealipg_next_post ) ); ?>" rel="next"><span><?php esc_html_e( 'Next Picture', 'peal333-infinite-picture-gallery' ); ?></span><strong><?php echo esc_html( $pealipg_next_title ); ?></strong></a>
								<?php endif; ?>
							</div>
						</nav>
					<?php endif; ?>
				<?php endif; ?>

				<div class="pealipg-back-row">
					<a class="pealipg-back-link" href="<?php echo esc_url( PEALIPG_Plugin::get_gallery_url() ); ?>">
						<span aria-hidden="true">&larr;</span>
						<?php esc_html_e( 'Back to Gallery', 'peal333-infinite-picture-gallery' ); ?>
					</a>
				</div>
			</article>

			<?php if ( $pealipg_detail_settings['enable_lightbox'] ) : ?>
				<div id="pealipg-lightbox" class="pealipg-lightbox" role="dialog" aria-modal="true" aria-labelledby="pealipg-lightbox-title" tabindex="-1" hidden>
					<h2 id="pealipg-lightbox-title" class="screen-reader-text"><?php esc_html_e( 'Image preview', 'peal333-infinite-picture-gallery' ); ?></h2>
					<button type="button" class="pealipg-lightbox-close" aria-label="<?php echo esc_attr__( 'Close image preview', 'peal333-infinite-picture-gallery' ); ?>">&times;</button>
					<div class="pealipg-lightbox-content"><img src="" alt=""></div>
				</div>
			<?php endif; ?>
		<?php endwhile; ?>
	</div>
</main>

<?php get_footer(); ?>
