<?php
/**
 * Single picture collection template.
 *
 * @package InfinitePictureGallery
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

get_header();
?>

<main id="primary" class="site-main ipg-site-main">
	<div class="ipg-single-wrapper">
		<?php while ( have_posts() ) : ?>
			<?php the_post(); ?>
			<article id="post-<?php the_ID(); ?>" <?php post_class( 'ipg-single-article' ); ?>>
				<header class="ipg-single-header">
					<?php
					$infinite_picture_gallery_title = get_the_title();
					if ( ! empty( $infinite_picture_gallery_title ) && '(no title)' !== $infinite_picture_gallery_title ) :
						?>
						<h1 class="ipg-single-title"><?php echo esc_html( $infinite_picture_gallery_title ); ?></h1>
					<?php endif; ?>
					<div class="ipg-single-date">
						<?php
						printf(
							/* translators: %s: Publication date. */
							esc_html__( 'Added on %s', 'peal333-infinite-picture-gallery' ),
							esc_html( get_the_date( 'F j, Y' ) )
						);
						?>
					</div>
				</header>

				<div class="ipg-single-content">
					<?php if ( has_post_thumbnail() ) : ?>
						<div class="ipg-cover-media">
							<?php
							$infinite_picture_gallery_cover = get_the_post_thumbnail( get_the_ID(), 'large', array( 'class' => 'ipg-cover-image' ) );
							// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core for the current post.
							echo $infinite_picture_gallery_cover;
							?>
						</div>
					<?php endif; ?>

					<?php
					$infinite_picture_gallery_description = get_post_meta( get_the_ID(), Infinite_Picture_Gallery::DESCRIPTION_META_KEY, true );
					if ( ! empty( $infinite_picture_gallery_description ) ) :
						?>
						<div class="ipg-description">
							<?php echo wp_kses_post( wpautop( $infinite_picture_gallery_description ) ); ?>
						</div>
					<?php endif; ?>
				</div>

				<?php
				$infinite_picture_gallery_gallery_ids = get_post_meta( get_the_ID(), Infinite_Picture_Gallery::GALLERY_META_KEY, true );
				$infinite_picture_gallery_ids_array   = array_values( array_filter( array_map( 'absint', explode( ',', (string) $infinite_picture_gallery_gallery_ids ) ) ) );
				if ( ! empty( $infinite_picture_gallery_ids_array ) ) :
					?>
					<div class="ipg-inner-gallery-grid">
						<?php foreach ( $infinite_picture_gallery_ids_array as $infinite_picture_gallery_attachment_id ) : ?>
							<?php if ( wp_attachment_is( 'video', $infinite_picture_gallery_attachment_id ) ) : ?>
								<?php
								$infinite_picture_gallery_video_url = wp_get_attachment_url( $infinite_picture_gallery_attachment_id );
								$infinite_picture_gallery_mime_type = get_post_mime_type( $infinite_picture_gallery_attachment_id );
								if ( ! $infinite_picture_gallery_video_url ) {
									continue;
								}
								?>
								<video controls playsinline preload="metadata">
									<source src="<?php echo esc_url( $infinite_picture_gallery_video_url ); ?>#t=0.5" type="<?php echo esc_attr( $infinite_picture_gallery_mime_type ); ?>">
									<?php esc_html_e( 'Your browser does not support the video tag.', 'peal333-infinite-picture-gallery' ); ?>
								</video>
							<?php else : ?>
								<?php
								$infinite_picture_gallery_image = wp_get_attachment_image( $infinite_picture_gallery_attachment_id, 'large', false, array( 'loading' => 'lazy' ) );
								// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress core for a known attachment ID.
								echo $infinite_picture_gallery_image;
								?>
							<?php endif; ?>
						<?php endforeach; ?>
					</div>
				<?php endif; ?>

				<div class="ipg-back-row">
					<a class="ipg-back-link" href="<?php echo esc_url( Infinite_Picture_Gallery::get_gallery_url() ); ?>">
						<span aria-hidden="true">&larr;</span>
						<?php esc_html_e( 'Back to Gallery', 'peal333-infinite-picture-gallery' ); ?>
					</a>
				</div>
			</article>
		<?php endwhile; ?>
	</div>
</main>

<?php get_footer(); ?>
